# 基本網站資訊
title: "點子實驗室 | Idea Hub"
description: "探索 AI、創意、創業與未來工具的專業內容平台"

# 使用簡單的 minima 主題
theme: minima

# 基本設定
url: "http://localhost:4000"
baseurl: ""

# 作者資訊
author:
  name: "Justin Lee"
  email: "madoka2024@email.com"

# Jekyll 設定
markdown: kramdown
highlighter: rouge
incremental: true

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# 排除檔案
exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - docker-compose-simple.yml
  - _config.yml
  - _config-simple.yml
  - "*.bat" 