services:
  jekyll:
    image: jekyll/jekyll:4
    container_name: idea-hub-jekyll
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    command: >
      bash -c "
      bundle config set --local path '/usr/local/bundle' &&
      bundle install --jobs 4 --retry 3 &&
      bundle exec jekyll serve --host 0.0.0.0 --config _config.yml,_config_dev.yml --livereload --force_polling --incremental
      "
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
      - node_modules:/srv/jekyll/node_modules
    stdin_open: true
    tty: true
    restart: unless-stopped  # 自動重啟容器

volumes:
  bundle_cache:
  node_modules: 