services:
  jekyll:
    image: jekyll/jekyll:4
    container_name: idea-hub-jekyll
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --host 0.0.0.0 --config _config.yml,_config_dev.yml --livereload --force_polling
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    stdin_open: true
    tty: true

volumes:
  bundle_cache: 