version: '3'
services:
  jekyll:
    image: jekyll/jekyll:3.8
    container_name: simple-jekyll
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --host 0.0.0.0 --livereload --force_polling --incremental
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll 